# Generated by Django 4.2.10 on 2024-02-10 17:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('DOWNLOADED', 'Downloaded')], default='CREATED', max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(choices=[('TS', '토스은행'), ('KB', 'KB국민은행'), ('SH', '신한은행'), ('WO', '우리은행'), ('NH', 'NH농협은행')], max_length=50)),
                ('bank_account', models.CharField(help_text='bank account number', max_length=100)),
            ],
            options={
                'unique_together': {('name', 'bank_name', 'bank_account')},
            },
        ),
        migrations.CreateModel(
            name='CertificateTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_id', models.CharField(max_length=100)),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='certificates.certificate')),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.user'),
        ),
    ]
