# Generated by Django 4.2.10 on 2024-02-10 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_alter_certificate_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetransfer',
            name='order',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
